#' @title Plotting results of sample.fluct
#' @param data = data.frame generated by the influential.analysis function.
#' @param parameter = Character. "var" for estimated variances, "load" for loadings.
#' @param variable = Character indicating the name of the observed variable to be plotted.
#' @param level = Integer indicating if focusing on level 1 or 2 (default).
#' @param threshold_lower = Numeric. Threeshold below which the participants'IDs are showed.
#' @param threshold_upper = Numeric. Threeshold above which the participants'IDs are showed.

plot.infl <- function(data,parameter="var",variable,level=2,
                      threshold_lower=NA,threshold_upper=NA){
  
  require(ggplot2)
  
  if(parameter=="var"){ par <- "variance"} else { par = "loading" }
  if(level==2){ colnames(data)[colnames(data)=="lv2"] <- "par" 
  } else { colnames(data)[colnames(data)=="lv1"] <- "par" }
  
  p <- ggplot(data[data$X==variable,],aes(ID,par))+
    geom_point()+ggtitle(paste(variable,par,"on level",level))+
    geom_point(data=data[data$X==variable & data$ID=="all",],colour="blue",size=5)+
    geom_point(data=data[data$X==variable & data$neg.var==1,],colour="red")+
    theme(axis.text.x = element_blank()) + xlab("")
  
  if(!is.na(threshold_lower) & is.na(threshold_upper)){
    p <- p + geom_text(data=data[data$X==variable & 
                                   data$par < threshold_lower,],
                       aes(label=ID),nudge_x=-5,size=3)
  } else if(is.na(threshold_lower) & !is.na(threshold_upper)){
    p <- p + geom_text(data=data[data$X==variable &
                                   data$par > threshold_upper,],
                       aes(label=ID),nudge_x=-5,size=3)
  } else if(!is.na(threshold_lower) & !is.na(threshold_upper)){
    p <- p + geom_text(data=data[data$X==variable & 
                                   (data$par > threshold_upper |
                                      data$par < threshold_lower),],
                       aes(label=ID),nudge_x=-5,size=3) }
  
  return(p)} 